// mainwindow.h
#pragma once
#include "model.h"
#include <QMainWindow>
#include <QImage>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    explicit MainWindow(QWidget* parent = nullptr);
    ~MainWindow();

private slots:
    void on_contentLabel_clicked();
    void on_styleLabel_clicked();
    void on_generateButton_clicked();

protected:
    bool eventFilter(QObject* obj, QEvent* ev) override;

private:
    Ui::MainWindow* ui;          // generated by uic, include below
    StyleTransferModel model;
    QImage contentImage;
    QImage styleImage;

    QImage cvMatToQImage(const cv::Mat& mat);
    cv::Mat qImageToCvMat(const QImage& img);
};
